import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <main className='flex flex-col gap-8 px-4 md:px-16 max-w-[1440px] mx-auto overflow-auto'>
        <Navbar/>
        {children}
        </main>
        </body>
    </html>
  )
}
